openapi: 3.0.1
info:
  description: Cartel API Documentation
  title: Cartel API
  version: 1.0.0
servers:
- url: //localhost:3000/api
paths: {}
components:
  schemas: {}
x-original-swagger-version: "2.0"

